import twitter from './img/twitter.png';
import opensea from './img/opensea.png';
import etherscan from './img/etherscan.png';
import connectWallet from './img/connect_wallet.png';
import mint from './img/mint.png';
import logo from './img/logo.png';
import video from './img/video.mp4';

import sample from './sample1.jpg';

function App() {
  return (
    <div className="container">
      <div className="logo-wrapper">
        <img src={logo} alt="" className='logo' />
      </div>
      <div className="wrapper">
        <div className="showcase">
          {/* <img src={sample} alt="" /> */}
          <video src={video} autoPlay loop muted></video>
        </div>
        <div className="mint-box">
          <div className="links">
            <a href="https://twitter.com/aishithappen">
              <img src={twitter} alt="" />
            </a>
            <a href="https://opensea.io/collection/aishithappen">
              <img src={opensea} alt="" />
            </a>
            <a href="">
              <img src={etherscan} alt="" />
            </a>
          </div>
          <div className="desc">
            <p>A collection of 10,000 turds uniquely crafted & generated by AI individually on the blockchain. Our promises are the nice unique shit. Let's explore your turd, it is fantasy, magical and unique.</p>
            <p>Take the Shit!</p>
            <p>It’s time for a change, make shit happen, gather motivation from around us and turn shit into gold, literally. Everyone is different; much like our collection, sometimes we are in a bad shape, but we always pull through and gain something and grow from that experience.</p>
            <p>Together, let’s Make Shit Happen!</p>
          </div>
          <button>
            <img src={connectWallet} alt="" />
          </button>
        </div>
      </div>
      <div className="banner">
        <div className="banner-text">
          <p>No Roadmap</p>
          <p>•</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>Shit Just Got Real</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>WAGMI</p>
        </div>
        <div className="banner-text">
          <p>No Roadmap</p>
          <p>•</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>Shit Just Got Real</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>WAGMI</p>
        </div>
        <div className="banner-text">
          <p>No Roadmap</p>
          <p>•</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>Shit Just Got Real</p>
          <p>Make Shit Happen</p>
          <p>•</p>
          <p>WAGMI</p>
        </div>
      </div>
    </div>
  );
}

export default App;
